version: "3"
services: 
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      mongodb_INITDB_DATABASE: pangea-assignment
    volumes:
      - ./db:/data/db  
    

  pangeaPublisher:
    image: flipponachi/pangea-publisher
    environment: 
      - MONGO_ADDRESS=db
    ports: 
      - "9000:9000"
    depends_on: 
      - db
    
  
  pangeaSubscriber:
    image: flipponachi/pangea-subscriber
    depends_on:
      - pangeaPublisher
    ports:
      - "4000:4000"
  
  

